# micro-recipient-service-recipient.yaml
apiVersion: v1
kind: Service
metadata:
  name: micro-recipient
spec:
  selector:
    app: micro-recipient
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP