global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['micro-sender:8081', 'micro-recipient:8082', 'micro-collector:8083']