# prometheus-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'micro-sender'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['micro-sender:8081']

      - job_name: 'micro-recipient'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['micro-recipient:8082']

      - job_name: 'micro-visualizer'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['micro-visualizer:8084']

      - job_name: 'micro-collector'
        metrics_path: '/actuator/prometheus'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - default
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: app
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod_name