spring:
  application:
    name: micro-collector
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: prometheus, metrics, health
  endpoint:
    prometheus:
      access: unrestricted
    metrics:
      access: unrestricted

server:
  port: 8083