spring:
  application:
    name: micro-recipient
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 1

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: prometheus, metrics, health
  endpoint:
    prometheus:
      access: unrestricted
    metrics:
      access: unrestricted
server:
  port: 8082